### ISSUE TITLE
Доступ к Score

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-api#26]
### По результатам анонса в Discord:
- 108 чел увидели свои оценки
- 66 чел не увидели свои оценки

### Фидбеки:
- У ментора https://github.com/DmitryRomaniuk/  - "no data"
- У нескольких активистов: 
     -  При попытке авторизации пишет {"message":"Too many requests, please try again later."}
     -  Сперва с телефона писал no data, потом открылся. Все оценки по нулям. С компа - опять no data
     - тоже самое, no data/ открывает / no data
     - cтуденты видят форму сабмита http://app.rs.school/task-score?course=rs-2019-q1

**Comment by apalchys** [comment]
Дима, похоже проблема в rate limiter была, который остался со старой версии и блочил часть запросов от UI сервера в пике. Я его убрал полностью и это должно решить большинство проблем.
Студенты теперь не должны видеть форму. Они и раньше не могли сабмитать ничего (проверка на сервере), теперь же я добавил проверку и на UI.

**Comment by dzmitry-varabei** [comment]
Спасибо @apalchys! Попросил проверить досуп к скору еще раз.

**Comment by AleksanderIII** [comment]
Отображается сообщение: You are not mentor in rs-2018-q3.

**Comment by alex-mnsk** [comment]
форма не сабмитится
и почему комментарий реквайред?

**Comment by themarkmarrone** [comment]
Ошибка при сабмите оценки  
![image](https://user-images.githubusercontent.com/18613713/57605371-2f7c3680-756f-11e9-8c3b-19f5c0184d63.png)

**Comment by apalchys** [comment]
@alex-mnsk попробуй пожалуйста сейчас. Проблема должна быть исправлена.

**Comment by apalchys** [comment]
комментарий скоро станет не обязательным.

**Comment by alex-mnsk** [comment]
@apalchys теперь ок
ещё было бы неплохо таймаут на месседж поставить, а то  если начать заполнять следующего студента, на сабмите уже непонятно сабмитнулось или нет

**Comment by eventpromo** [comment]
Студент не выполнил задание, поле PR является обязательным, следовательно я не могу сабмитить форму, так как не имею PR.

**Comment by apalchys** [comment]
@eventpromo принято. подумаем как лучше такое сделать, так как пока цель формы трекать именно сделанное. 
Можешь чуть подробнее описать, что ты хотел сабмитнуть? Просто 0 как скор или что-то больше?

**Comment by eventpromo** [comment]
> @eventpromo принято. подумаем как лучше такое сделать, так как пока цель формы трекать именно сделанное.
> Можешь чуть подробнее описать, что ты хотел сабмитнуть? Просто 0 как скор или что-то больше?

Да, просто 0 хотел отправить.

**Comment by alex-mnsk** [comment]
@eventpromo а зачем так делать, по дефолту и так 0

**Comment by eventpromo** [comment]
> @eventpromo а зачем так делать, по дефолту и так 0

Как минимум показать, что я не забыл про него и, возможно, оставить какой-нибудь комментарий.

**Comment by alex-mnsk** [comment]
@eventpromo так в скоре он видит 0 и ничего больше

**Comment by MSt1ch** [comment]
![image](https://user-images.githubusercontent.com/17798957/57627337-7afb0880-75a0-11e9-99d3-7ad05c1aa66a.png)
в таске  Hexal нету PR и я не могу отправить форму с оценкой.

**Comment by apalchys** [comment]
@MSt1ch Проверь пожалуйста сейчас

**Comment by ollyyasinski** [comment]
Не вижу своего студента в дропдауне скор
Мой гитхаб: https://github.com/ollyyasinski
Гитхаб студента: https://github.com/rolling-scopes-school/felcilive-2019Q1

**Comment by DaryaHaprova** [comment]
у моего студента https://github.com/rolling-scopes-school/KirillFilipp-2019Q1 нет баллов по заданию Code Jam "CORE JS" в score

**Comment by arsafab** [comment]
не вижу своих студентов в 
![image](https://user-images.githubusercontent.com/25402078/57936983-b44bb500-78cd-11e9-8544-28b5c0bef759.png)

**Comment by mrsDandelion** [comment]
У студентов ildorado, oxanadanilova, gerasik, nij4life, forkossigan стоят оценки за code jam 'palette', хотя оценки еще не ставили и только начали проверять.

**Comment by apalchys** [comment]
@arsafab пока students страница не доступна для публичного пользования. (добавлю приписку).
Чуть позже выкатим.
Пока можно найти и увидеть студентов в score

**Comment by apalchys** [comment]
@mrsDandelion да, извини. была проблема и залились неверные результаты. откатили и сейчас должно быть ок.

**Comment by apalchys** [comment]
@ollyyasinski исправлено.

**Comment by artyom123** [comment]
Не вижу своего студента https://github.com/sagero

**Comment by Atzkdeff** [comment]
Мой студент хотел поменять ник на гитхабе на более благозвучный. В общем-то и поменял но потерял доступ к http://app.rs.school/ . Возможно ли это пофиксить или лучше уже оставить ник до конца курса, т.к. он во всех формах завязан?

**Comment by apalchys** [comment]
@Atzkdeff Напиши пожалуйста старый и новый ник студента. Я поменяю в базе данных и он снова получит доступ.

**Comment by Atzkdeff** [comment]
@apalchys старый - "Pytniza", новый - "13-friday". https://github.com/13-friday

**Comment by apalchys** [comment]
@Atzkdeff готово. пусть проверит. 
![image](https://user-images.githubusercontent.com/618807/58387070-e8cc1900-8011-11e9-88cc-5170fc5caffc.png)

**Comment by dzmitry-varabei** [comment]
@ollyyasinski 
@DaryaHaprova 
@arsafab 
@mrsDandelion
@artyom123 

Если у вас остались какие-то проблемы c данными, опишите проблему, пожалуйста, еще раз вот сюда - #44

Этот тред закрываем, ввиду отсутствия тестеров и ожидания, что фиксы принесли эффект.
Спасибо!

**Comment by eventpromo** [comment]
При клике на шапку происходит редирект к задаче. При этом срабатывает еще какая-то сортировка, но не совсем по баллам за данный таск (по которому был совершен клик). Предлагаю реализовать рядом с названием стрелочку или что-то подобное, по которой будет совершаться сортировка, а переход к таске по клику на название.
