### ISSUE TITLE
Функционал для исправления оценки в Score.

### ISSUE THREAD

**Issue by MikhailLU** [rolling-scopes/rsschool-api#30]
- если ментор ошибся с выставленной оценкой, было бы здорово иметь возможность изменить/отменить результат

**Comment by apalchys** [comment]
@MikhailLU можно еще раз сабмитнуть оценку по тому же таску - она "исправит" старую. (чтобы отменить - можно указать 0 и комментарий что отмена)

**Comment by apalchys** [comment]
Закрываю.
