### ISSUE TITLE
RS 2019-Q1: Score Data Issues

### ISSUE THREAD

**Issue by apalchys** [rolling-scopes/rsschool-api#31]
Issue для трекинга проблем с данными
- неверный скор
- нету скора
т.д.

Указывайте, если возможно, пожалуйста github студента и имя таска

**Comment by devbarden** [comment]
Сабмитал оценки двум студентам в гугл форму ещё неделю назад: 
- https://github.com/zzsshalik
- https://github.com/Zamtakaish 
Не подтянулись оценки в приложении до сих пор

**Comment by themarkmarrone** [comment]
нет оценок у
https://github.com/yuliyasamsonova
https://github.com/lavfrim 
https://github.com/deminiro
https://github.com/VictoriaButrym

по Task Markup Neutron Mail
в гугл форме сабмитнуты 5/10/2019

**Comment by apalchys** [comment]
@devbarden укажи пожалуйста для каких тасков были оценки

**Comment by Tatsiya** [comment]
У двух студентов нет оценок за NeutronMail - githubs: 
https://github.com/Vad199it
https://github.com/Ulfahedin

**Comment by devbarden** [comment]
@apalchys Hexal, NeutronMail, Code jam pallete

**Comment by shpakkdv** [comment]
https://github.com/GeorgeTuz
https://github.com/katyYats
нет оценок по Hexal и NeutronMail

**Comment by egor-suzanovich** [comment]
у двух студентов 
https://github.com/Tanya92
https://github.com/oldblacktree

нет оценок по таскам: NeutronMail, CodeJam-dom Palette

**Comment by mariakravchenko** [comment]
https://github.com/olgaluk
https://github.com/leonidshparun

нету оценок за CodeJam-dom Palette

**Comment by SiarheiMelnik** [comment]
> Сабмитал оценки двум студентам в гугл форму ещё неделю назад:
> 
> * https://github.com/zzsshalik
> * https://github.com/Zamtakaish
>   Не подтянулись оценки в приложении до сих пор

**Comment by SiarheiMelnik** [comment]
Проадейтал скор по Hexal, Neutron Mail, Code Jam "Palette". @devbarden @Tatsiya @egor-suzanovich @shpakkdv @mariakravchenko @themarkmarrone пожалуйста проверьте.

**Comment by devbarden** [comment]
@SiarheiMelnik да, всё есть.

**Comment by greatorangejuice** [comment]
greatorangejuice
Нет оценок по Neutron Mail, CodeJam Palette

**Comment by m1kash** [comment]
https://github.com/m1kash
Нет оценок по Code Jam "Palette", Code Jam "CoreJS"

**Comment by lion9** [comment]
Нет ни единой оценки в скоре.

**Comment by vovikilelik** [comment]
https://github.com/Venul
- Имя студента указано с префиксом школы - https://github.com/Venul-2019Q1, стр: 648 
- Неверно указано название таска, 648 стр. Должно быть Task Markup Neutron Mail вместо Stage #1 Hexal
- Неверно указан скор для Stage #1 CV (GIt & HTML & CSS), 1137 стр, Нужно 70.
- Неверно указан скор для Hexal, 1138 стр, Нужно 90.

**Comment by vovikilelik** [comment]
https://github.com/eugene-bobrovnik
Гитхаб студента указан с префиксом школы - https://github.com/eugene-bobrovnik-2019Q1
Строки: 449, 467, 469, 1136

**Comment by alexalizurchik** [comment]
https://github.com/alexalizurchik
Нет оценки по Code Jam "Palette"

**Comment by pavel-leskavets** [comment]
Нет оценки по NeutronMail, ментор больше недели не выходит на связь

**Comment by ihargit** [comment]
[https://github.com/ihargit](url)
Нет оценки за Code Jam "Corejs"

**Comment by plusch011** [comment]
нет оценок за CoreJs CodeJam Palette
https://github.com/plusch011

**Comment by Alexfario** [comment]
Нет студента,
mentor: https://github.com/Alexfario
student: https://github.com/slayer110

**Comment by dzmitry-varabei** [comment]
@lion9 Ментор выставлял какие-нибудь оценки? У нас никаких данных нет

**Comment by SiarheiMelnik** [comment]
@Alexfario проверь пожалуйста, должен появиться

**Comment by SiarheiMelnik** [comment]
@ihopeyouwin Ментор выставлял какие-нибудь оценки? У нас никаких данных нет

**Comment by plusch011** [comment]
CoreJS 0 баллов стоит


>Пятница, 17 мая 2019, 13:46 +03:00 от Siarhei Melnik <notifications@github.com>:
>
>@Alexfario проверь пожалуйста, должен появиться
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Влад Павлющик

**Comment by ihargit** [comment]
Ментор еще не залил оценку за Palette, a в скоре уже стоит https://monosnap.com/file/DN87j8y6CIOQOKTKnaHQMilukodPTN

**Comment by greatorangejuice** [comment]
https://github.com/greatorangejuice
Добавили неправильную оценку по Code Jam Palette. Должно быть 140

Все еще отсутствуют оценки по Neutron Mail и CoreJs. 
И суммируются оценки, которые выставлены сейчас неправильно. 
![image](https://user-images.githubusercontent.com/43197939/57926883-2c59b100-78b5-11e9-94d4-e7c4fbdf6da5.png)

**Comment by plusch011** [comment]
это наверное не ко мне


>Пятница, 17 мая 2019, 15:05 +03:00 от Pavel Snigirev <notifications@github.com>:
>
>https://github.com/greatorangejuice
>Добавили неправильную оценку по Code Jam Palette. Должно быть 140
>Все еще отсутствуют оценки по Neutron Mail и CoreJs.
>И суммируются оценки, которые выставлены сейчас неправильно.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Влад Павлющик

**Comment by Spinnen87** [comment]
Работа за pallette ещё не проверялась. А оценка стоит 100. Ментор PR не Серджио еще

**Comment by JuliaMV** [comment]
Сегодня появилась оценка за pallete - 100, но ментор ещё не проверял это задание

**Comment by yanaSelin** [comment]
Аналогично, еще не проверяла pallette, но у студентки стоит оценка. (студент - https://github.com/IrynaZhadzinets)

**Comment by MitskevichVS** [comment]
https://github.com/MitskevichVS
Изменилась оценка за palette, вчера была та, которую выставил ментор, сегодня ниже

**Comment by m1kash** [comment]
https://github.com/m1kash
Изменилась оценка за palette, вчера была та, которую выставил ментор, сегодня ниже

**Comment by Alexfario** [comment]
> @Alexfario проверь пожалуйста, должен появиться

@SiarheiMelnik -  увы, ещё нет, смотрю по селекту из секции по выставлению оценки

**Comment by ihargit** [comment]
Это сообщение не ко мне

**Comment by apalchys** [comment]
@greatorangejuice общий скор теперь с учетом коэффициентов к каждому таску.
у CV - 0.2, Hexal - 0.5

**Comment by apalchys** [comment]
@SiarheiMelnik  у `slayer110` ментор почему-то `NikitaRudy`

**Comment by SiarheiMelnik** [comment]
@apalchys у slayer110 два ментора alexfario и NikitaRudy потому что он учился в разное время

**Comment by SiarheiMelnik** [comment]
> > @Alexfario проверь пожалуйста, должен появиться
> 
> @SiarheiMelnik - увы, ещё нет, смотрю по селекту из секции по выставлению оценки

![image](https://user-images.githubusercontent.com/3370693/57936707-18ba4480-78cd-11e9-81d3-300ca0e83095.png)

**Comment by apalchys** [comment]
@Spinnen87  @JuliaMV @IrynaZhadzinets
Спасибо. Исправили - был ошибочный апдейт.

@MitskevichVS @m1kash
Проверьте пожалуйста похожи ли оценки на те, что были.

**Comment by greatorangejuice** [comment]
Оценку одну поправили, теперь Palette верно отображен. Но по остальным таскам: CoreJs, Neytron баллов нет

**Comment by apalchys** [comment]
@vovikilelik  можешь пожалуйста исправить оценки по таскам через форму сабмита для своего студента. Оно имеет мержить результат.
http://app.rs.school/task-score?course=rs-2019-q1

**Comment by MitskevichVS** [comment]
@apalchys у меня все ок, спасибо

**Comment by SiarheiMelnik** [comment]
> Аналогично, еще не проверяла pallette, но у студентки стоит оценка. (студент - https://github.com/IrynaZhadzinets)

@yanaSelin

**Comment by SiarheiMelnik** [comment]
@Alexfario вернули тебе студента slayer110

**Comment by plusch011** [comment]
>

Нет оценок! plusch011
Влад Павлющик

**Comment by Anna-Pronovich** [comment]
Нет оценки  https://github.com/Anna-Pronovich  -  CodeJam-dom Palette

**Comment by ksandrsis** [comment]
нет оценок в принципе 
https://github.com/ksandrsis

**Comment by lion9** [comment]
https://github.com/lion9
Нет ни единой оценки в скоре. Ни от ментора - обещал проверить таски выставить, но не выставил, похоже, ни парсингом

**Comment by apalchys** [comment]
@dzmitry-varabei 
Обрати внимание, что делать людям, когда ментор забил:
>https://github.com/lion9
Нет ни единой оценки в скоре. Ни от ментора - обещал проверить таски выставить, но не выставил, похоже, ни парсингом

>https://github.com/pavel-leskavets
Нет оценки по NeutronMail, ментор больше недели не выходит на связь


@ksandrsis @lion9 
смотрим почему нету оценок за первую stage

@Anna-Pronovich Похоже ментор не выставлял. Уточни пожалуйста у него, сабмитал ли он (мы не видим в системе)

@plusch011 Есть все кроме `Pallete`. Похоже ментор еще не выставлял (нету в системе)

@alexalizurchik @greatorangejuice @ihargit CoreJS fixed

**Comment by CodingRuslan** [comment]
Нет оценки https://github.com/CodingRuslan - Code Jam CoreJs
Сабмитал во время, в скоре на падавансах баллы были

**Comment by Alexfario** [comment]
@SiarheiMelnik спасибо, да, вижу

**Comment by dzmitry-varabei** [comment]
@lion9 @pavel-leskavets Если ваш ментор до сих пор не вышел на связь - напишите, пожалуйста, в дискорде Pavel Razuvalau#6656.

**Comment by OlgaMardvilko** [comment]
@apalchys @dzmitry-varabei 
Добрый день! Возникла ситуация, что не вижу одного из своих студентов. Вероятнее причина в том, что изначально был назначен другой ментор. 

Проблемы: 
- не могу выставить оценки 
- у студента отсутствуют оценки, ранее выставляемые мной через форму
- у студента за все таски стоит 0 

Можно ли закрепить за мной студента и выставить оценки в скор?

студент: [https://github.com/Julanick](https://github.com/Julanick )
ментор: [https://github.com/OlgaMardvilko](https://github.com/OlgaMardvilko)

**Comment by apalchys** [comment]
@OlgaMardvilko обновил. теперь Julanick твой студент. проверь пожалуйста.

**Comment by OlgaMardvilko** [comment]
@apalchys, спасибо! Студент появился. А по оценкам, кроме тех, что я могу выставить, что-то должно появиться?

**Comment by OlgaMardvilko** [comment]
@apalchys , спасибо! Студент появился. А по оценкам, кроме тех, что я могу выставить, что-то должно появиться?
Могу я попросить добавить оценки  [https://github.com/Julanick](https://github.com/Julanick) по следующим таскам:
Code Jam "CoreJS" 
Codewars

**Comment by OlgaMardvilko** [comment]
@apalchys Огромное спасибо! Все появилось. Вопросов больше нет)

**Comment by apalchys** [comment]
@OlgaMardvilko да, только хотел написать. все должно быть ок сейчас

**Comment by apalchys** [comment]
@CodingRuslan проверь пожалуйста.

**Comment by CodingRuslan** [comment]
@apalchys Все на месте, спасибо

**Comment by dzmitry-varabei** [comment]
@devbarden, @themarkmarrone, @Tatsiya, @shpakkdv
@Tatsiya @egor-suzanovich @mariakravchenko @greatorangejuice
@m1kash @lion9 @vovikilelik @alexalizurchik @pavel-leskavets
@ihargit @ihopeyouwin @plusch011 @Alexfario
@plusch011 @ihargit @greatorangejuice @JuliaMV @yanaSelin @m1kash

Если у вас остались какие-то проблемы c данными, опишите проблему, пожалуйста, еще раз вот сюда - https://github.com/rolling-scopes/rsschool-api/issues/44

Этот тред закрываем, ввиду отсутствия тестеров и ожидания, что фиксы принесли эффект.
Спасибо!
