### ISSUE TITLE
Несоответствие скора

### ISSUE THREAD

**Issue by Oigen43** [rolling-scopes/rsschool-api#34]
За cv стоит 25, а ментор ставил 100
Мой гитхаб: [https://github.com/Oigen43](https://github.com/Oigen43)

**Comment by apalchys** [comment]
@Oigen43 В тех данных что у нас есть, стоит только 25

@eugenechyrski подскажи, какая верная оценка? И если все-таки ошибка, можешь пожалуйста пересабмитать.

**Comment by dzmitry-varabei** [comment]
@Oigen43 

Если у вас остались какие-то проблемы c данными, опишите проблему, пожалуйста, еще раз вот сюда - https://github.com/rolling-scopes/rsschool-api/issues/44

Этот тред закрываем, ввиду отсутствия тестеров и ожидания, что фиксы принесли эффект.
Спасибо!
