### ISSUE TITLE
Несоответствие пар студент-ментор для набора 2018-Q3

### ISSUE THREAD

**Issue by mikhama** [rolling-scopes/rsschool-api#38]
По запросу:
http://app.rs.school/api/profile?githubId=mikhama

Вижу что `data.students.mentor.user.githubId === 'olgamardvilko'`. (Это выражение верно в том случае, если речь идет об интервью на 2-м стэйже). Но ментор должен быть `nikitzu`.

Скорее всего перепутаны таблица с парами студент-ментор c таблицей для интервью по coreJs.

**Comment by dzmitry-varabei** [comment]
@mikhama @SiarheiMelnik есть какие-то новости?

**Comment by mikhama** [comment]
@dzmitry-varabei пока что тот ментор, который проводил собес, числится.

**Comment by SiarheiMelnik** [comment]
@dzmitry-varabei даже еще не смотрел. а можно как-то пометить приоритетные таски ?

**Comment by SiarheiMelnik** [comment]
@mikhama да я залил пары из стадии 2. исправил. @apalchys залей пожалуйста данные из rs_pairs_2018Q3

**Comment by SiarheiMelnik** [comment]
@mikhama этот ишьюс еще актуален ?

**Comment by mikhama** [comment]
Уже нет. Закрываю. Спасибо!
