### ISSUE TITLE
Submit Video & Presentation: You are not student in rs-2019-q1.

### ISSUE THREAD

**Issue by AndreySomov** [rolling-scopes/rsschool-api#42]
При переходе на страницу добавления презентации, http://app.rs.school/task-artefact?course=rs-2019-q1 на самой странице выдает You are not student in rs-2019-q1;
https://imgur.com/a/59a0qVE
В общем скоре мой ник не горит серым, значит система не считает меня отчисленным 
https://imgur.com/a/NXmM5nl
GitHub аккаунт не менял, проверено на нескольких устройствах.

**Comment by AndreySomov** [comment]
https://github.com/AndreySomov

**Comment by apalchys** [comment]
@AndreySomov исправлено. спасибо.
