### ISSUE TITLE
New students in my group

### ISSUE THREAD

**Issue by pavelrazuvalau** [rolling-scopes/rsschool-api#46]
Привет! Ко мне присоединились два новых студента от других менторов, а именно:
Pavel Leskavets (pavel-leskavets)
Artyom Vecherov (lion9)
Хотелось бы им оценки выставить за предыдущие таски.
Сейчас в app.rs.school их не вижу, по сему хотелось бы видеть их у меня в группе
И еще в моем списке нет Andrej Rozhnov (AcetonKZ), но его я собрался отчислить.

Спасибо!

**Comment by apalchys** [comment]
готово. теперь они твои студенты. @pavelrazuvalau проверь.
AcetonKZ уже получился отчислен, так как у него не было ментора.

**Comment by pavelrazuvalau** [comment]
Спасибо! Issue можно закрыть
