### ISSUE TITLE
Некорректное распределение пар 'студент-ментор' для собеседований по Core JS

### ISSUE THREAD

**Issue by mikhama** [rolling-scopes/rsschool-api#52]
Мой студент с `githubId = gyegor` отсутствует в списке совсем. В то время как для студента с `githubId = sergey-xursevich` отображается очень много менторов. И таких студентов много.

**Comment by BarikQ** [comment]
Там же видно, что только пару студентов почти у всех менторов

**Comment by ihargit** [comment]
Моего ника github нету в списке. Ник ihargit

**Comment by AnastasiyaBaranovskaya** [comment]
и моего нет в списке Anastasiyabaranovskaya

**Comment by alexgrist14** [comment]
Нет ника в списке alexgrist14

**Comment by m1kash** [comment]
Моего ника в списке нету m1kash

**Comment by Jeka98** [comment]
нет ника в списке Jeka98

**Comment by ekater1na** [comment]
Меня тоже нет ekater1na

**Comment by Evgeni-Borovik** [comment]
Отсутствует ник Evgeni-Borovik

**Comment by Sergey-Xursevich** [comment]
Ссылаюсь на очень большое количество менторов githubId = sergey-xursevich 😀

**Comment by Toffifi** [comment]
Нет в списке Toffifi

**Comment by MyPersonalAcc** [comment]
Нет в спискe MyPersonalAcc

**Comment by 200hp** [comment]
Нет в списке 200hp

**Comment by felcilive** [comment]
Мой студент с githubId = felcilive отсутствует в списке совсем.

**Comment by annazankevich** [comment]
нет ника annazankevich

**Comment by vladji** [comment]
Зачем всем писать свои ники, которых там нет, если в списке всего 4  студента распределены на всех менторов

**Comment by mikhama** [comment]
Пока предлагаю не писать. Просто отмечайтесь пальцем вверх кто есть и пальцем вниз кого нет под  этим сообщением.

**Comment by alex91pro** [comment]
Alex91pro нет

**Comment by andreiButenka** [comment]
andreiButenka нет в списке.

**Comment by slava-ff** [comment]
У slava-ff нет ментора

**Comment by daryanovak** [comment]
daryanovak нет ментора

**Comment by mbulldozer** [comment]
mbulldozer нет ментора

**Comment by mbulldozer** [comment]
mbulldozer нет ментора

**Comment by BarikQ** [comment]
Там же видно что в списках студентов всего человек 10 повторяющихся. 
BarikQ - нет в списках

**Comment by SiarheiMelnik** [comment]
Спасибо что помогли с тестированием

**Comment by vishnevsky533** [comment]
![изображение](https://user-images.githubusercontent.com/47160955/58637747-e44a7d80-82fb-11e9-97ba-d5b9f3ec592e.png)

**Comment by mikhama** [comment]
Пожалуйста, проверьте, как сейчас распределились пары?
Поставьте пальцы вверх - если у вас есть ментор.
И вниз - если ментора нет.

**Comment by tracktorina** [comment]
👎

**Comment by mikhama** [comment]
@tracktorina - есть ментор, я вижу. Это там еще один баг (в ui составляющей), оно пробелы не обрезает. Попробуй введи еще раз свой логин.

**Comment by PraKDown** [comment]
Это конечный результат распределения? Можно ли уже писать ментору?

**Comment by Slider7** [comment]
Дорый день. За последние 24 часа у меня ментор поменялся 3 раза: вначале был ментор Пасюкевич, вчера вечером - стала Гребенчук, сегодня с утра решил перепроверить перед отправкой письма и вижу что новый ментор - https://github.com/AleksanderIII. Уточните пожалуста, может пока лучше подождать когда окончательно список утрясется. Не хотелось бы зря человека тревожить. т.е. этот список окончательный или нет? Большое Спасибо.

**Comment by m1kash** [comment]
Выбило ментора из могилева,  мой github m1kash

**Comment by IrinaBorkina** [comment]
а мне из минска снова ментор, хотя я из могилева

**Comment by dzmitry-varabei** [comment]
@m1kash @IrinaBorkina это не имеет значения

**Comment by nixon2105** [comment]
сразу выбило один ник ментора для собеседования, через минут 5 зашел уже другой ник

**Comment by dzmitry-varabei** [comment]
@nixon2105 похоже на баг

**Comment by IrinaBorkina** [comment]
тоже изменился  ментор

**Comment by mbulldozer** [comment]
mbulldozer - ментор есть, но из москвы, хотя сам в минске

**Comment by Cassinix** [comment]
themarkmarrone - мой ментор для собеса, остутствует в таблице с контактами

**Comment by BarikQ** [comment]
lipnitsky93 - мой ментор отсутствует на github и в таблице с контактами

**Comment by IrinaBorkina** [comment]
они есть, по поиску поищите

**Comment by Cassinix** [comment]
а как я по-твоему ищу?)

**Comment by IrinaBorkina** [comment]
![1](https://user-images.githubusercontent.com/44750544/58701770-89249380-83ac-11e9-97b7-a8e114e9fa05.PNG)

**Comment by IrinaBorkina** [comment]
![image](https://user-images.githubusercontent.com/44750544/58701822-b2452400-83ac-11e9-8b59-e97fc21ea786.png)

**Comment by Cassinix** [comment]
Их не было там пару минут назад, Ctrl+S и Ctrl+F не может поломаться

**Comment by IrinaBorkina** [comment]
хромовский поиск не ищет, надо нажимать на ячейку какую-нибудь в таблице и через ctrl+f в документе искать, тож такая проблема изначально возникла

**Comment by hausfrau** [comment]
Нет контактных данных ментора mariakravchenko.

**Comment by VeronikaVasilchikova** [comment]
Привет! Нет контактных данных ментора cheekeebreekee

**Comment by cathzetjo** [comment]
После двухнедельного отсутствия мой ментор Алексей (github=unsafefunction) вышел на связь сообщил, что у него  больше нет возможности вести/собеседовать студентов. 
1. Нужно по возможности кому-то отдать его студентов ( не проверено два последних таска - ютуб и презентация).
2. Для текущего рандомного собеседования  нужно назначить студентам, попавшим к нему, другого ментора.

**Comment by IharTsykala** [comment]
А это нормально если я из Минска а ментор на интервью из Москвы?

**Comment by dzmitry-varabei** [comment]
@IharTsykala да, это норм

**Comment by diesel167** [comment]
У моего ментора https://github.com/AnLeonovich из способов связи только её гитхаб. Написал на почту указанную в гитхабе, вчера, но ответа пока нет. Можно ли попросить уточнить иные способы связи с ней?

**Comment by apalchys** [comment]
@diesel167 http://app.rs.school/mentor-contacts?course=rs-2019-q1 проверь тут

**Comment by 505Flamingo** [comment]
505Flamingo нет в списке

**Comment by apalchys** [comment]
@505Flamingo добавил
