### ISSUE TITLE
Выбрасывает из приложения при клике по gitID

### ISSUE THREAD

**Issue by AlexKelle** [rolling-scopes/rsschool-api#56]
Chrome v 74.0.3729.169 
MacOS Mojave v 10.14.5
Клик по ссылки в announsments.
Поиск по gitID
Клик на gitID ментора.
Ожидаемый результат: Переход к git или контактам ментора
Фактический результат: перенаправляется на главную страницу

**Comment by apalchys** [comment]
@AlexKelle к сожалению, profile ментора как и студента доступен только админу из-за личных данных (телефон, емейл и т.д.). Есть планы ее улучшить и показывать информацию в зависимости от роли и разрешений, но это на будущее.

Есть пока отдельная страница, где можно посмотреть контакты своего ментора или интервьювера
http://app.rs.school/mentor-contacts?course=rs-2019-q1
