### ISSUE TITLE
Лишний студент в списке

### ISSUE THREAD

**Issue by pavelkeyzik** [rolling-scopes/rsschool-api#59]
На странице Submit Score в выпадающем списке Student у меня 2 стуента, Владимир и Роман. Роман был принят на курсы, но через неделю была заполнена форма на отчисление.

**Actual result**: У меня 2 студента Vladmimir Malygin и Roman Khaliulin
**Expected result**: Должен видеть только Vladmimir Malygin

**Comment by apalchys** [comment]
@pavelkeyzik если не трудно, можешь воспользоваться вот этой формой и исключить студента сам. После этого он должен стать задизейблен.

http://app.rs.school/expel?course=rs-2019-q1

**Comment by pavelkeyzik** [comment]
@apalchys Отправил форму. Студент пока остался в списке, но я подожду

**Comment by pavelkeyzik** [comment]
Сори.. Он просто disabled. Я понял) Спасибо
