### ISSUE TITLE
Некорректное отображение в выпадающем списке на COREJS: INTERVIEW FEEDBACK

### ISSUE THREAD

**Issue by eventpromo** [rolling-scopes/rsschool-api#61]
В выпадающий список попадают все студенты заасайненные на меня.
![image](https://user-images.githubusercontent.com/4561476/59923135-4d289f80-943b-11e9-878f-1c3d45183028.png)
![image](https://user-images.githubusercontent.com/4561476/59923140-56197100-943b-11e9-9136-4ecdb9642a8b.png)

**Comment by apalchys** [comment]
Будет исправлено в завтрашнем обновлении. Спасибо.

**Comment by apalchys** [comment]
@eventpromo Закрываю, так как проблема исправлена.
