### ISSUE TITLE
Персональные данные ментора

### ISSUE THREAD

**Issue by marusyaganza** [rolling-scopes/rsschool-api#63]
Не предоставлять студентам номер телефона ментора без согласия последнего. Студенты могут пользоваться skype/ telegram контактом ментора, который он предоставил.

**Comment by apalchys** [comment]
@marusyaganza 
Завтра уберу этот функционал. Извините за неудобства.
Изначально добавили из-за большого количества просьба/вопросов как связаться с ментором.

P.S.
:( Заметил этот issue только сегодня, так как не получаю нотификации там где я не упомянут.
