### ISSUE TITLE
Photo resizing in profile

### ISSUE THREAD

**Issue by cathzetjo** [rolling-scopes/rsschool-api#75]
In profile photo doesn’t shows correctly.

![DA1E69C4-E701-449A-B89B-9BE03B78CC58](https://user-images.githubusercontent.com/44948376/62460640-38099500-b78b-11e9-91d0-3c769f17bab5.jpeg)

**Comment by apalchys** [comment]
@cathzetjo thanks for catching it in Safari. Fixed.
