### ISSUE TITLE
Zero points for all people of 2018-Q3 course

### ISSUE THREAD

**Issue by DimaDK24** [rolling-scopes/rsschool-api#76]
**Course**
2018-Q3

**What is wrong**
In the previous versions of RS School App [score of 2018-Q3](http://app.rs.school/course/score?course=rs-2018-q3) was correct.

Now it shows people in the incorrect order and shows zero points in total for everyone and for the majority of people zero points for every single task  😿

**Comment by apalchys** [comment]
fixed. thanks!
