### ISSUE TITLE
I am "gray" in the score, but i am active student

### ISSUE THREAD

**Issue by slava-ff** [rolling-scopes/rsschool-api#77]
**Course**
rs-2019-q1

**What is wrong**
I am "gray" in the score, but i am active student. I hope I am not expelled, and this is just a mistake. My mentor @anv21 says she didn't do anything.
My GitHub ID is @slava-ff (#135 in a score now)

**Comment by apalchys** [comment]
i'm really sorry. it was a fault on the backend side. fixed.

**Comment by slava-ff** [comment]
It's okay, thanks))
