### ISSUE TITLE
Отчисления

### ISSUE THREAD

**Issue by Hellsingi** [rolling-scopes/rsschool-api#82]
**Describe the bug**
Добрый день. я показываюсь как отчисленый, но меня ментор не отчисляя.
ник Github Hellsingi

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by dzmitry-varabei** [comment]
@Hellsingi отчислен, так как не сдан piskel clone.
