### ISSUE TITLE
I can't give a grade for the assignment to my student

### ISSUE THREAD

**Issue by AntonAtrashkou** [rolling-scopes/rsschool-api#83]
1. Go to 'http://app.rs.school/course/mentor/check-task?course=rs-2019-q1'
2. Select task for example CodeJam "Animation Player"
3. Сhoose student
4. Doen't pass validation writes that the field is required

** Expected Behavior **
Student data autofill without verification error and the ability to evaluate the task

![image](https://user-images.githubusercontent.com/36513369/62736006-221efd00-ba35-11e9-8545-f85aa919a93f.png)

**Comment by apalchys** [comment]
Fixed. @AntonAtrashkou please check

**Comment by AntonAtrashkou** [comment]
Checked, everything works fine. Thank you for fast fix!
