### ISSUE TITLE
Ошибочно отчислен

### ISSUE THREAD

**Issue by HyBeard** [rolling-scopes/rsschool-api#84]
После обновления обнаружил, что пополнил ряд отчисленных, хотя ментор меня к таковым не относил.

![image](https://user-images.githubusercontent.com/47788411/62839954-55fb5c00-bc9b-11e9-9899-0d3c0c413eb7.png)

**Comment by dzmitry-varabei** [comment]
@HyBeard отчислен, так как не проверен piskel clone.
@apalchys issue закрываю.
