### ISSUE TITLE
My profile - error - no data

### ISSUE THREAD

**Issue by cathzetjo** [rolling-scopes/rsschool-api#85]
When you go to http://app.rs.school/profile you can see next error message:
![Screenshot_2019-08-12_141156](https://user-images.githubusercontent.com/44948376/62861275-9bf00880-bd0b-11e9-8a84-7d6b3765b9d1.jpg)

**Comment by amoebiusss** [comment]
the same problem
Win 10, Chrome 75

**Comment by apalchys** [comment]
Fixed. Some changes were pushed too early. Thanks for catching!
